env:
  global:
    secure: "pjCub1n/YxROvFHPNQCtdSOHYxAzFAKbxfIv/q+ANEGuuM8DTvE0KrcCPM/QWH1I6stnwrkwScE+Es8+A529T8gxZPqHO1MxEy28v8ObQnb/Ai5rB58tdVBZKpDHmjNd26mxn9vJX8/n+l60r5/dznNQtjtMeRBkKtsD/2JtR0E="

language: php

cache:
    directories:
        - $HOME/.composer

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - cd ..
  - git clone https://github.com/mapbender/mapbender-starter
  - cd mapbender-starter
  - git checkout develop
  - if (test $TRAVIS_PULL_REQUEST = false) then git checkout $TRAVIS_BRANCH; fi
  - git submodule update --init --recursive
  - cd application
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer update
  - rm -rf mapbender
  - ln -s ../../mapbender
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Epsg/ --append
  - php app/console fom:user:resetroot --username root --password root --email root@root.de --silent
  - phantomjs --webdriver=9876 &
  - export PJSPORT=$(echo $!)
  - pip install selenium

script: phpunit -c app/ --coverage-clover ../testresults/clover.xml

after_script:
  - php bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - cd mapbender
  - export MYREV=$(git rev-parse HEAD)
  - cd ..
  - php ocular.phar code-coverage:upload --repository g/mapbender/mapbender --format=php-clover ../testresults/clover.xml --revision $MYREV
  - kill -9 $PJSPORT
  - echo -e "Host mapbender3.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo apt-get -qq update
  - sudo apt-get -qq install sshpass
  - sshpass -p "$travispassword" ssh travis@mapbender3.org mkdir -p public/screenshot/$TRAVIS_JOB_NUMBER/
  - sshpass -p "$travispassword" scp ../testresults/screenshot/* travis@mapbender3.org:public/screenshot/$TRAVIS_JOB_NUMBER/
