language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  - cd ..
  - git clone https://github.com/mapbender/mapbender-starter
  - cd mapbender-starter
  - git checkout feature/testing
  - git submodule update --init --recursive
  - cd application
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer update --dev
  - rm -rf mapbender
  - ln -s ../../mapbender
  - phantomjs --webdriver=9876 &
script: phpunit -c app/
after_script:
  - php bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - cd mapbender
  - export MYREV=$(git rev-parse HEAD)
  - cd ..
  - cat /tmp/weblog
  - php ocular.phar code-coverage:upload --repository g/mapbender/mapbender --format=php-clover ../testresults/clover.xml --revision $MYREV
