parameters:
    applications: []
    sources: []
    config_check_extensions: []

    mapbender.branding.name: Mapbender
    mapbender.version: 4.2.4
    mapbender.branding.logo: bundles/mapbendercore/image/logo_mb_notext.png
    # These should all remain empty here, they are just for IDE search results.
    # Customize these in your parameters.yaml.
    # The name will show up in page titles; the version will show in your backend;
    # the logo will display on your login page, the backend again, and some of the application templates.
    branding.project_name: ~
    branding.project_version: ~
    branding.logo: ~                # public-relative path
    branding.splashscreen_image: ~  # public-relative path. Falls back to branding.logo.
    # splashscreen_image can be an object with application id as keys and "default" as the default image

    # default image for Mapbender 4: Beinn Dorain, Scotland,
    # captured by Thorsten Hack (@phocacius on unsplash): https://unsplash.com/de/fotos/gewasser-in-der-nahe-des-berges-tagsuber-yCUVfiEw3nA
    branding.login_backdrop: ~
    branding.login_backdrop_hq: ~

    # Sitelinks displayed below login box and backend content
    # Should be a list of items each with keys 'link' and 'text'
    mapbender.sitelinks: []

    mapbender.asset_overrides: ~
    mapbender.icons.disable_default: false
    mapbender.icons.disable_default_fa: false
    mapbender.icons.custom: ~

