jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOM\UserBundle\Entity\User: sha512

    providers:
        main:
            entity:
                class: FOM\UserBundle\Entity\User
                property: username

    acl:
        connection: default

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /user/login/check
                login_path: /user/login
            logout:
                path:   /user/logout
                target: /

    access_control:
        - { path: ^/user/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager,       roles: ROLE_USER }

